language: cpp
matrix:
    include:
        - os: osx
          compiler: clang
          addons:
              apt:
                  sources:
                      - llvm-toolchain-precise-3.7
                  packages:
                      - clang-3.7
script:
    - mkdir build && cd build
    - cmake ..
    - make -C build
    - make -C build test ARGS="-VV"
