language: cpp

addons:
    apt:
        packages:
            - gcc-4.9
            - gcc-5
            - clang-3.7
            - cmake
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7

matrix:
    include:
        - os: osx
          compiler: clang-3.7
          env: CLANG_VERSION=3.7
        - os: linux
          env: GCC_VERSION=4.9
        - os: linux
          env: GCC_VERSION=5

install:
    - |
      if [[ -n "$CLANG_VERSION" ]]; then
        export CXX=clang++-$CLANG_VERSION CC=clang-$CLANG_VERSION;
      fi
    - |
      if [[ -n "$GCC_VERSION" ]];
        then export CXX=g++-$GCC_VERSION CC=gcc-$GCC_VERSION;
      fi
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir -p "${DEPS_DIR}"
    - cd "${DEPS_DIR}"
    - |
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        if [[ -z "$(ls -A ${DEPS_DIR}/cmake/bin)" ]]; then
            CMAKE_URL="https://cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz"
            mkdir -p cmake
            travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" |
                tar --strip-components=1 -xz -C cmake
        fi
        export PATH="${DEPS_DIR}/cmake/bin:${PATH}"
      else
        if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
      fi

script:
    - BUILD_DIR="${TRAVIS_BUILD_DIR}/build"
    - mkdir -p "${BUILD_DIR}"
    - cd "${BUILD_DIR}"
    - cmake ..
    - make 
    - make test ARGS="-VV"
