language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
        packages:
            - g++-4.9
            - g++-5
            - clang-3.6
            - clang-3.7

os:
    - linux
    - osx

script:
    - mkdir build && cd build
    - cmake .. && make
