language: cpp

addons:
    apt:
        packages:
            - gcc-4.9
            - gcc-5
            - clang-3.7
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7

matrix:
    include:
        - os: osx
          compiler: clang-3.7
        - os: linux
          compiler: gcc-4.9
        - os: linux
          compiler: gcc-5

script:
    - mkdir build
    - cd build
    - cmake ..
    - make 
    - make test ARGS="-VV"
